### ISSUE TITLE
SCSS: integrates two font-family

### ISSUE THREAD

**Issue by Skaant** [Skaant/rimarok-2#14]
The two families to include (experimental) :
* Font 1 - **Rubik 400** (for texts)
  https://fonts.google.com/specimen/Rubik
* Font 2 - **Roboto Slab 300** (for titles, displays, headers)
  https://fonts.google.com/specimen/Roboto+Slab

1. [x] Add fonts file in `/static/fonts` (create folder `static`, more info : https://www.gatsbyjs.com/docs/how-to/images-and-media/static-folder/)
2. [x] Create font families in `global.scss` :
  The font face & a `font-*` class to add in components' `className`.
  Example : https://github.com/Skaant/highbs-bok/blob/6880ab499e2d3affc12944f5e1a51ed919163b90/src/styles/global.scss#L62-L68
  ```scss
  @font-face {
    font-family: "Rubik-400";
    src: url("/fonts/<file-name>");
  }
  
  .font-rubik {
    font-family: "Rubik-400";
  }
  ```

* `Rubik-400` alias : 'rubik' (for `.font-rubik`)
* `Roboto-Slab-300` alias : 'slab' (for `.font-slab`)
